/**
 * Milliken Contracting — Image Manifest
 * Maps all 26 project images to metadata for site-wide use.
 * See docs/IMAGE-CONTENT-PLAN.md for full analysis.
 */

export type ImageOrientation = 'landscape' | 'portrait' | 'square';
export type ImagePriority = 1 | 2 | 3 | 4 | 5; // 1 = highest
export type BeforeAfterRole = 'before' | 'after' | null;

export interface ImageManifestEntry {
  id: string;
  filename: string;
  alt: string;
  category: string;
  tags: string[];
  orientation: ImageOrientation;
  featured: boolean;
  heroCandidate: boolean;
  recommendedPlacement: string[];
  priority: ImagePriority;
  serviceAssociations: string[];
  projectGroup: string | null;
  beforeAfter: BeforeAfterRole;
  notes: string;
  cropRecommendation: string | null;
}

const IMAGES_BASE = '/images';

export const imageManifest: ImageManifestEntry[] = [
  {
    id: '1-pre',
    filename: '1-pre.jpg',
    alt: 'Victorian house porch restoration in progress with stone foundation',
    category: 'process',
    tags: ['restoration', 'porch', 'stone', 'victorian', 'during'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['about', 'projects-before-after'],
    priority: 4,
    serviceAssociations: ['restorations', 'renovations'],
    projectGroup: 'victorian-restoration',
    beforeAfter: 'before',
    notes: 'Work-in-progress; tools, vacuum, tarp visible. Process shot only.',
    cropRecommendation: null,
  },
  {
    id: '1-1',
    filename: '1.1.jpg',
    alt: 'Custom exterior wooden staircase with turned balusters and lattice',
    category: 'exterior',
    tags: ['stairs', 'porch', 'custom-carpentry', 'balusters', 'lattice'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: false,
    recommendedPlacement: ['home-featured', 'projects', 'services-exteriors'],
    priority: 2,
    serviceAssociations: ['restorations', 'custom-woodwork', 'exteriors'],
    projectGroup: 'victorian-restoration',
    beforeAfter: null,
    notes: 'Strong craftsmanship; trash bin and bag in frame. Crop recommended.',
    cropRecommendation: 'Crop out trash bin and bag on left',
  },
  {
    id: '1',
    filename: '1.jpg',
    alt: 'Victorian house exterior with ornate woodwork and decorative gable',
    category: 'exterior',
    tags: ['victorian', 'restoration', 'woodwork', 'historic', 'gable'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: true,
    recommendedPlacement: ['hero', 'home-featured', 'projects', 'services-restorations'],
    priority: 1,
    serviceAssociations: ['restorations', 'exteriors', 'custom-woodwork'],
    projectGroup: 'victorian-restoration',
    beforeAfter: 'after',
    notes: 'Intricate balusters, lattice, colorful gable. Minor: recycling bins left.',
    cropRecommendation: null,
  },
  {
    id: '2',
    filename: '2.jpg',
    alt: 'Modern white staircase with cable railing and shingle siding',
    category: 'exterior',
    tags: ['staircase', 'modern', 'addition', 'railing', 'cable'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: false,
    recommendedPlacement: ['home-featured', 'projects', 'services-additions'],
    priority: 2,
    serviceAssociations: ['additions', 'exteriors'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Clean staircase; unfinished dirt, generator visible. Crop bottom 20-25%.',
    cropRecommendation: 'Crop bottom to remove dirt and generator',
  },
  {
    id: '3',
    filename: '3.jpg',
    alt: 'Custom angled wood door with Z-bracing and wrought iron hinges',
    category: 'interior',
    tags: ['custom-woodwork', 'door', 'detail', 'interior'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: false,
    recommendedPlacement: ['projects', 'services-custom-woodwork', 'about'],
    priority: 2,
    serviceAssociations: ['custom-woodwork', 'renovations'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Excellent craftsmanship, clean. Best as detail shot.',
    cropRecommendation: null,
  },
  {
    id: '4',
    filename: '4.jpg',
    alt: 'Interior hallway with herringbone brick floor and shiplap walls',
    category: 'interior',
    tags: ['flooring', 'herringbone', 'brick', 'shiplap', 'entryway'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: true,
    recommendedPlacement: ['hero', 'home-featured', 'projects', 'services-renovations'],
    priority: 1,
    serviceAssociations: ['renovations', 'interior-finishes'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Strong pattern, textures. Exposed electrical boxes; crop or retouch.',
    cropRecommendation: 'Crop or retouch electrical boxes and drain grate',
  },
  {
    id: '5',
    filename: '5.jpg',
    alt: 'Light wood staircase with diagonal metal balusters',
    category: 'interior',
    tags: ['staircase', 'millwork', 'railing', 'interior'],
    orientation: 'portrait',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects', 'services-renovations'],
    priority: 3,
    serviceAssociations: ['renovations', 'custom-woodwork'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Great railing; debris, wires, unfinished walls. Tight crop on railing.',
    cropRecommendation: 'Tight crop on staircase and railing only',
  },
  {
    id: '5-1',
    filename: '5.1.jpg',
    alt: 'Modern railing with horizontal black spindles and windows',
    category: 'interior',
    tags: ['railing', 'millwork', 'windows', 'interior'],
    orientation: 'portrait',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects', 'services-renovations'],
    priority: 3,
    serviceAssociations: ['renovations', 'custom-woodwork'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Good composition; concrete floor, debris. Process/detail use.',
    cropRecommendation: null,
  },
  {
    id: '6',
    filename: '6.jpg',
    alt: 'Circular oculus window with curved wall integration',
    category: 'interior',
    tags: ['window', 'custom', 'architectural', 'interior'],
    orientation: 'portrait',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects', 'services-custom-woodwork', 'about'],
    priority: 3,
    serviceAssociations: ['custom-woodwork', 'renovations'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Unique feature; power drill on sill. Retouch or crop out drill.',
    cropRecommendation: 'Retouch or crop out power drill on windowsill',
  },
  {
    id: '7',
    filename: '7.jpg',
    alt: 'Interior with diagonal hardwood floor, staircase, and French doors',
    category: 'interior',
    tags: ['flooring', 'staircase', 'living-space', 'premium'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: true,
    recommendedPlacement: ['hero', 'home-featured', 'projects', 'contact-background'],
    priority: 1,
    serviceAssociations: ['renovations', 'interior-finishes'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Clean, unfurnished, strong design. Primary hero candidate.',
    cropRecommendation: null,
  },
  {
    id: '8',
    filename: '8.jpg',
    alt: 'Exposed wooden truss in vaulted ceiling',
    category: 'interior',
    tags: ['timber-frame', 'truss', 'custom-build', 'craftsmanship'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: false,
    recommendedPlacement: ['home-featured', 'projects', 'services-custom-woodwork', 'about'],
    priority: 1,
    serviceAssociations: ['custom-woodwork', 'additions'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Impressive craftsmanship; construction lights, scaffolding.',
    cropRecommendation: null,
  },
  {
    id: '8-1',
    filename: '8.1.jpg',
    alt: 'Fluted beam and timber framing detail',
    category: 'interior',
    tags: ['timber-frame', 'beam', 'custom', 'craftsmanship'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: false,
    recommendedPlacement: ['projects', 'services-custom-woodwork', 'about'],
    priority: 2,
    serviceAssociations: ['custom-woodwork', 'additions'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Unique fluted detail. Yellow wire, scaffolding. Process/craftsmanship.',
    cropRecommendation: 'Detail crop on fluted beam only',
  },
  {
    id: '9',
    filename: '9.jpg',
    alt: 'Modern shower with marble-look tile and hexagonal floor',
    category: 'bathroom',
    tags: ['bathroom', 'shower', 'tile', 'marble'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: true,
    recommendedPlacement: ['hero', 'home-featured', 'projects', 'services-bathrooms'],
    priority: 1,
    serviceAssociations: ['bathrooms'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Polished, finished. Minor exposed framing right edge.',
    cropRecommendation: null,
  },
  {
    id: '10',
    filename: '10.jpg',
    alt: 'Ornate porch column with gothic spandrels',
    category: 'exterior',
    tags: ['porch', 'column', 'restoration', 'detail'],
    orientation: 'portrait',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['services-restorations', 'projects'],
    priority: 4,
    serviceAssociations: ['restorations', 'exteriors'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Peeling paint, sawhorse visible. Crop to column detail only.',
    cropRecommendation: 'Tight crop on column capital; exclude sawhorse',
  },
  {
    id: '11',
    filename: '11.jpg',
    alt: 'Grey composite deck with white railings',
    category: 'exterior',
    tags: ['deck', 'outdoor', 'railing', 'composite'],
    orientation: 'portrait',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects', 'services-additions'],
    priority: 3,
    serviceAssociations: ['additions', 'outdoor'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Clean deck; unfinished gable, orange sheathing in background.',
    cropRecommendation: 'Crop to focus on deck and railing',
  },
  {
    id: '11-pre',
    filename: '11-pre.jpg',
    alt: 'Deck framing on roof with joists and dormer',
    category: 'process',
    tags: ['framing', 'addition', 'structural', 'during'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['about', 'services-additions'],
    priority: 4,
    serviceAssociations: ['additions'],
    projectGroup: null,
    beforeAfter: 'before',
    notes: 'Structural detail. Ladder, building wrap. Process/About.',
    cropRecommendation: null,
  },
  {
    id: '12',
    filename: '12.jpg',
    alt: 'Front porch with gray decking and white railings',
    category: 'exterior',
    tags: ['porch', 'decking', 'railing', 'entryway'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: false,
    recommendedPlacement: ['home-featured', 'projects', 'services-exteriors'],
    priority: 2,
    serviceAssociations: ['exteriors', 'renovations'],
    projectGroup: 'porch-94',
    beforeAfter: 'after',
    notes: 'Clean, modern. Exposed ceiling beams; neighbor house in bg.',
    cropRecommendation: null,
  },
  {
    id: '12-before',
    filename: '12..jpg',
    alt: 'House before porch renovation',
    category: 'before',
    tags: ['before', 'porch', 'renovation'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects-before-after'],
    priority: 5,
    serviceAssociations: ['renovations', 'exteriors'],
    projectGroup: 'porch-94',
    beforeAfter: 'before',
    notes: 'Clearly "before." Use only paired with 12.jpg after.',
    cropRecommendation: null,
  },
  {
    id: '12-2',
    filename: '12.2.jpg',
    alt: 'White house with front porch',
    category: 'exterior',
    tags: ['exterior', 'porch', 'renovation'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects'],
    priority: 5,
    serviceAssociations: ['exteriors', 'renovations'],
    projectGroup: 'porch-94',
    beforeAfter: null,
    notes: 'Power lines, satellite dish, generic. Portfolio filler at best.',
    cropRecommendation: null,
  },
  {
    id: '12-pre',
    filename: '12-pre.jpg',
    alt: 'Porch renovation in progress with caution tape',
    category: 'process',
    tags: ['during', 'porch', 'renovation', 'construction'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects-before-after', 'about'],
    priority: 5,
    serviceAssociations: ['renovations', 'exteriors'],
    projectGroup: 'porch-94',
    beforeAfter: null,
    notes: 'During construction. Use with 12.. (before) and 12 (after) for full story.',
    cropRecommendation: null,
  },
  {
    id: '13',
    filename: '13.jpg',
    alt: 'Wooden canopy frame over entrance during construction',
    category: 'process',
    tags: ['canopy', 'exterior', 'custom-carpentry', 'during'],
    orientation: 'portrait',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['about', 'services-exteriors'],
    priority: 4,
    serviceAssociations: ['exteriors', 'custom-woodwork'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'New canopy; ladder, exposed wrap. Process/About.',
    cropRecommendation: 'Tight crop on canopy structure',
  },
  {
    id: '14',
    filename: '14.jpg',
    alt: 'Stone-clad steps with black railings and red door',
    category: 'exterior',
    tags: ['entryway', 'stone', 'railing', 'porch'],
    orientation: 'portrait',
    featured: true,
    heroCandidate: false,
    recommendedPlacement: ['home-featured', 'projects', 'services-exteriors'],
    priority: 2,
    serviceAssociations: ['exteriors', 'renovations'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Strong stonework. Drink bottle, old walkway. Crop recommended.',
    cropRecommendation: 'Crop out drink bottle, old walkway, leaves',
  },
  {
    id: '15',
    filename: '15.jpg',
    alt: 'Blue house with porch and balcony',
    category: 'exterior',
    tags: ['exterior', 'porch', 'balcony'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects'],
    priority: 5,
    serviceAssociations: ['exteriors', 'additions'],
    projectGroup: null,
    beforeAfter: 'after',
    notes: 'Truck visible, exposed lumber, balcony clutter.',
    cropRecommendation: 'Crop to remove truck; still weak',
  },
  {
    id: '15-pre',
    filename: '15-pre.jpg',
    alt: 'House with new porch structure during construction',
    category: 'process',
    tags: ['during', 'addition', 'porch'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['projects-before-after', 'about'],
    priority: 5,
    serviceAssociations: ['additions', 'exteriors'],
    projectGroup: null,
    beforeAfter: 'before',
    notes: 'Truck, bins. Process only.',
    cropRecommendation: null,
  },
  {
    id: '18',
    filename: '18.jpg',
    alt: 'Victorian house with wraparound porch during restoration',
    category: 'process',
    tags: ['victorian', 'restoration', 'porch', 'during'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['about', 'services-restorations'],
    priority: 4,
    serviceAssociations: ['restorations'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Wheelbarrow, tools, tarps. During-construction.',
    cropRecommendation: null,
  },
  {
    id: '18-1',
    filename: '18.1.jpg',
    alt: 'Brick porch with columns during restoration',
    category: 'process',
    tags: ['restoration', 'porch', 'brick', 'during'],
    orientation: 'landscape',
    featured: false,
    heroCandidate: false,
    recommendedPlacement: ['about', 'services-restorations'],
    priority: 4,
    serviceAssociations: ['restorations'],
    projectGroup: null,
    beforeAfter: null,
    notes: 'Tarp, ladder, tools. Work-in-progress.',
    cropRecommendation: null,
  },
];

// --- Helpers ---

export function getImagePath(entry: ImageManifestEntry): string {
  return `${IMAGES_BASE}/${entry.filename}`;
}

export function getImageById(id: string): ImageManifestEntry | undefined {
  return imageManifest.find((e) => e.id === id);
}

export function getHeroCandidates(): ImageManifestEntry[] {
  return imageManifest.filter((e) => e.heroCandidate);
}

export function getFeaturedImages(): ImageManifestEntry[] {
  return imageManifest.filter((e) => e.featured);
}

export function getImagesByService(serviceSlug: string): ImageManifestEntry[] {
  return imageManifest.filter((e) =>
    e.serviceAssociations.some((s) => s.toLowerCase().includes(serviceSlug.toLowerCase()))
  );
}

